package com.lwt.qmqiu.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lwt.qmqiu.bean.DownloadFileDb;

import com.lwt.qmqiu.greendao.DownloadFileDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadFileDbDaoConfig;

    private final DownloadFileDbDao downloadFileDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadFileDbDaoConfig = daoConfigMap.get(DownloadFileDbDao.class).clone();
        downloadFileDbDaoConfig.initIdentityScope(type);

        downloadFileDbDao = new DownloadFileDbDao(downloadFileDbDaoConfig, this);

        registerDao(DownloadFileDb.class, downloadFileDbDao);
    }
    
    public void clear() {
        downloadFileDbDaoConfig.clearIdentityScope();
    }

    public DownloadFileDbDao getDownloadFileDbDao() {
        return downloadFileDbDao;
    }

}
